class Inputs:
    # Requirements and design/search choices; provisional assumptions are identified below.
    magnet_lateral_edge = 5                     # mm; square permanent-magnet block edge in the Halbach array
    magnet_thickness = 4                        # mm; baseline block thickness, not a newly optimized value
    magnets_per_period = 4                      # blocks per spatial magnetic period
    periods_per_side = 1                        # magnetic periods along each side of the piece array
    coils_per_period = 2                        # coil pitches per spatial magnetic period
    coil_outer_length = 15                      # mm; long outside dimension of each rectangular coil
    winding_radial_width = 1.0                  # mm; winding wall available to copper, insulation and clearance
    control_cells_per_side = 4                  # coil-pitch cells along each side of the local actuation window
    magnet_to_coil_distance = 3.5               # mm; nominal magnet-bottom to top-coil gap in flight
    max_flight_gap = 4.5                        # mm; upper magnet-to-coil gap sampled for flight authority and sensing
    plastic_wall_thickness = 1.0                # mm; hollow piece-shell wall used in the mass estimate
    piece_shell_shape_factor = 0.6              # ratio of hollow king bounding-cylinder shell mass/inertia retained uniformly; provisional silhouette approximation
    worst_phase_dwell = 0.5                     # s; flight takeoff dwell, charged at worst sampled hover power
    cruise_duration = 1.5                       # s (atomic move A: up to full-diagonal flight in this window)
    selected_bus_voltage = 40                   # V; retained full-bus baseline with a controlled midpoint; not re-optimized
    landing_dwell = 0.5                         # s (aligned-slot approach and settle)
    events_back_to_back = 2                     # count (immediate-rematch resets with no cooldown)
    sustained_event_period = 300                # s (one full reset event sustained forever)
    play_move_period = 6                        # s per composite move in the passive-cooling sustained workload
    sustained_moves_per_minute = 10             # composite moves/min in the fan-assisted workload; user-approved sustained target, checked against serial move timing
    replay_capture_fraction = 0.25              # ratio (replay moves that add a second storage flight)
    replay_knight_gap_fraction = 0.15           # ratio (replay moves needing blockers to part and re-close)
    hammer_visit_period = 5                     # s; T3 repeat period for a dwell on the same cell
    hammer_dwell = 1.0                          # s; T3 aligned hover dwell per visit
    cascade_exchanges = 10                      # exchanges in the T3 burst; each contributes two local dwells
    coil_bed_temp_limit = 105                   # C; internal winding/potting acceptance limit; touch limits are checked separately
    force_safety_factor = 1.3                   # ratio; required lift reserve above piece weight
    min_maneuver_accel_g = 0.2                  # g; minimum horizontal flight acceleration, also checked against travel timing
    min_visible_hover_height = 3                # mm (piece bottom to playing surface at nominal hover)
    min_level_hover_endurance = 30              # s; retained continuous parked-hover requirement; no thermal-governor credit
    min_showpiece_hover_endurance = 3           # s; retained deepest-tilt hover requirement on one cell
    tilt_rim_clearance = 1.0                    # mm (tilt limited so the lowest rim point keeps this clearance above the playing surface)
    target_tilt_time = 0.3                      # s
    target_yaw_angle_deg = 90                   # deg
    target_yaw_time = 0.5                       # s
    ambient_temperature = 35                    # C
    max_surface_temperature = 50                # C; baseplate-temperature acceptance limit in the current thermal screen
    control_loop_bandwidth_margin = 5           # ratio; heuristic multiplier on nominal unstable growth rate, not a closed-loop stability proof
    pieces_levitating_simultaneously = 1        # airborne pieces in normal play; independent of the reset population
    drive_look_ahead_factor = 1.5               # ratio; extra driven-channel allowance around the active flight footprint
    active_cooling_fans = 2                     # fans in the fan-assisted thermal scenario; passive scenario uses no fans
    reset_duration = 8.0                        # s; provisional full-set contact-reset duration, not a routing guarantee
    reset_breakaway_duration = 0.5              # s; provisional static-friction phase within reset_duration
    production_boards = 100                     # boards per production order used to label the BOM cost assumptions
    piece_count = 32                            # pieces in the full set, contact reset and total storage capacity
    max_tip_position_error = 0.001              # m; maximum lateral tip error inferred from Hall tilt uncertainty
    max_surface_flatness_fraction = 0.25        # ratio; allowed surface flatness budget divided by visible hover height
    platform_side_limits = (20, 50)             # mm; accepted lower and upper bounds for the square magnetic platform
    trajectory_force_margin = 1.05              # ratio; acceleration reserve on the full-diagonal triangular motion profile
    selected_conductor_thickness = 0.05         # mm; adopted bare-copper thickness from the winding screen; supplier confirmation outstanding
    selected_winding_layers = 57                # axial layers; adopted prototype winding, with turns per layer defined in Fixed
    standard_bus_voltages = (24, 30, 40, 48)    # V; bus candidates for the preliminary winding screen
    winding_conductor_thicknesses = (selected_conductor_thickness, 0.07, 0.1, 0.15, 0.2, 0.3, 0.4, 0.5) # mm; bare rectangular-copper thickness candidates; supplier availability unverified


class Fixed:
    # Implementation, numerical and costing assumptions, not immutable physical constants.
    # Historical component specifications and prices require validation before hardware selection.
    base_corner_standoff = 8                    # mm
    square_fill_ratio = 0.8                     # ratio (maximum; actual fill falls out of period snapping)
    max_chess_square_size = 60                  # mm
    resting_friction_coefficient = 0.4          # ratio; assumed static friction for reset breakaway and powered-off no-snap checks
    captured_side_areas = 2                     # motorized storage areas flanking the playing board
    herringbone_orientation_families = 2        # count
    reference_king_height = 95                  # mm
    reference_king_base_diameter = 44           # mm
    rectangular_wire_film = 0.012               # mm per face; assumed enamel thickness, to be confirmed with the wire supplier
    turns_per_radial_layer = 1                  # count
    nominal_coil_height_for_field = 1.0         # mm; reference winding height for the preliminary field/coupling screen
    potting_thickness = 0.5                     # mm (dispensed epoxy bed between coil bottoms and PCB; thinned for the hot-copper local stack)
    potting_thermal_conductivity = 2.5          # W/(m.K) Appli-Thane 7300 class thermal potting
    potting_volumetric_heat_capacity = 2300000.0 # J/(m3.K) (volume-weighted: ~21% copper walls + filled-epoxy windows)
    coil_bed_through_conductivity = 2.0         # W/(m.K) (through-plane: enamel-film wire stack in parallel with potted coil windows)
    potting_cover_thickness = 0.2               # mm (self-leveling skim over coil tops)
    playing_surface_thickness = 0.1             # mm (UV-printed graphics + clear wear topcoat directly on the potting; no separate sheet)
    playing_surface_conductivity = 0.2          # W/(m.K) epoxy topcoat
    piece_bottom_skin = 0.1                     # mm (plated magnets flush, thin conformal coat)
    surface_flatness_budget = 0.3               # mm (over full board span)
    max_touch_temperature = 77                  # C; retained brief-touch screening limit applied to every cell, even when covered; material/contact validation outstanding
    prolonged_touch_temperature = 48            # C; retained prolonged-touch screening limit for idle surface regions
    magnet_max_operating_temperature = 150      # C (SH-grade NdFeB rating; resting piece soaks toward the cell temperature)
    pcb_via_effective_thermal_conductivity = 10 # W/(m.K) (dense 0.3mm thermal-via array under the coil bed, ~1mm pitch)
    thermal_pad_conductivity = 5.0              # W/(m.K) premium dispensed gap filler
    baseplate_thickness = 4.0                   # mm
    aluminium_thermal_conductivity = 167        # W/(m.K)
    aluminium_density = 2700                    # kg/m3
    aluminium_heat_capacity = 900               # J/(kg.K)
    fin_height = 60                             # mm; retained heatsink geometry, not resized for the new motion scenarios
    fin_thickness = 2                           # mm
    fin_channel_width = 8                       # mm
    natural_convection_coefficient = 2          # W/(m2.K) (derated: fins face down under an elevated board)
    forced_convection_coefficient = 8           # W/(m2.K)
    cooling_fan_size = 200                      # mm
    cooling_fan_speed = 550                     # rpm
    cooling_fan_airflow = 100.8                 # m3/h
    cooling_fan_static_pressure = 0.51          # mm H2O
    cooling_fan_noise = 10.7                    # dB(A)
    cooling_fan_installation_noise = 3          # dB(A)
    cooling_fan_airflow_fraction = 0.25         # ratio
    cooling_fan_power = 0.96                    # W
    cooling_fan_mass = 0.37                     # kg
    cooling_fan_price = 39.95                   # USD
    cooling_fan_url = 'https://www.coolerguys.com/products/noctua-nf-a20-pwm-200mm-cooling-fan' # historical fan listing used for the BOM; not a refreshed quotation
    mosfet_voltage_rating = 60                  # V
    min_mosfet_voltage_headroom = 1.5           # ratio; MOSFET voltage rating divided by candidate bus voltage must meet this value
    driver_channel_current = 5.5                # A per coil; regulated cycle-average capability, distinct from instantaneous device/protection rating
    driver_peak_current = 6.5                   # A per coil; provisional instantaneous power-stage/protection capability including switching ripple
    driver_max_ripple_current = 0.5             # A; allowed peak deviation from cycle-average current in the split-rail PWM screen
    driver_pwm_frequency = 160000               # Hz; provisional carrier target set by the low-inductance ripple screen, not pose control
    current_regulator_rate = 20000              # Hz; sampled current-regulator update rate, independent of the PWM carrier
    driver_switching_time = 1e-07               # s
    driver_hot_resistance = 0.08                # ohm
    driver_mosfet_gate_charge = 3e-08           # C
    gate_drive_voltage = 10                     # V
    logic_gate_voltage = 5                      # V
    current_command_rate = 4000                 # Hz; driver setpoint update rate, distinct from pose feedback, current-loop bandwidth and PWM
    pose_feedback_rate = 1000                  # Hz; conservative candidate pose-estimation/feedback rate, to be tested rather than minimized
    pose_controller_frequency = 20             # Hz; natural frequency of the candidate six-axis critically damped pose controller
    pose_controller_damping = 1                 # ratio; candidate second-order pose-controller damping
    pose_observer_frequency_ratio = 2           # ratio; position/velocity/disturbance observer pole frequency divided by pose-controller natural frequency
    qualification_sensor_latency = 0.001        # s; assumed maximum additional pose-estimate age at the feedback tick
    qualification_position_error = 0.00016      # m; bounded vector magnitude of injected position error, provisional sensing requirement
    qualification_angle_error = 0.005           # rad; bounded vector magnitude of injected orientation error, provisional sensing requirement
    qualification_mass_fraction = 0.1           # ratio; symmetric mass uncertainty about the bottom-heavy geometric king estimate
    qualification_com_fraction = 0.2            # ratio; symmetric COM-height uncertainty about the geometric king estimate
    qualification_inertia_fraction = 0.25        # ratio; symmetric uncertainty in each principal moment of inertia
    qualification_inductance_factors = (0.5, 2) # ratio; screening bounds on unmeasured self-inductance; mutual inductance remains unmodeled
    qualification_recovery_duration = 0.25       # s; local hover disturbance-recovery observation window
    qualification_initial_error_fraction = 0.25 # ratio; initial translation/tilt disturbance relative to their existing position/tip budgets
    qualification_noise_bias_fraction = 0.5     # ratio; share of bounded sensor error assigned to constant bias, remainder to a sinusoid
    qualification_integration_substeps = 2      # count; averaged mechanical/electrical integration steps per current-regulator update
    qualification_field_rate = 4000            # Hz; numerical magnetic-force refresh rate, independent of physical feedback and command rates
    qualification_refinement_factor = 2         # ratio; independent time and force-mesh refinement for the worst tested trajectory
    qualification_parallel_workers = 3          # processes; independent dynamic cases run with separate simulator geometry state
    qualification_convergence_fraction = 0.05   # ratio; numerical tolerance relative to tracking budgets, reserved current, and observed peak electrical power
    qualification_current_reserve_fraction = 0.1 # ratio; minimum unused channel-current capacity in the tested demand envelope
    qualification_current_transient_allowance = 0.1 # A; extra allocation headroom for regulator transients, beyond sense offset and command quantization
    setpoint_filter_passive_price = 0.003       # USD per 15.8k + 10nF pair (catalog target; production RFQ needed)
    setpoint_filter_cutoff = 1000               # Hz
    max_setpoint_bits = 12                      # count
    max_current_command_error = 0.005           # A
    current_loop_bandwidth = 2000               # Hz; assumed inner current-regulation bandwidth, not a sampling rate
    min_current_loop_samples = 8                # ratio; current-regulator samples per current-loop bandwidth
    min_setpoint_serial_headroom = 1.2          # ratio (parallel logical-board serializer lanes are sized above the quantization minimum)
    current_sense_resistance = 0.02             # ohm
    comparator_input_offset = 0.005             # V (LM393 raw, removed by idle zero-calibration)
    current_sense_offset_residual = 0.001       # V (post-calibration drift: comparator + level-shift divider tempco over the operating range)
    max_current_offset_fraction = 0.05          # ratio of driver limit
    current_shunt_price = 0.0418                # USD (Milliohm HoJLR2512-2W-20mR-1% 75ppm, LCSC C2924538 at 4k; full-reel RFQ pending)
    current_shunt_power_rating = 2              # W
    current_comparator_channels_per_ic = 2      # count
    current_comparator_price = 0.0198           # USD
    current_frontend_passives_per_channel = 4   # count (RC filter + midpoint level-shift pair; 1% + matched arrays suffice - idle zero-cal removes statics)
    current_frontend_passive_price = 0.0035     # USD (1% thick-film + matched-pair arrays where tracking matters)
    driver_gate_passive_price = 0.0012          # USD
    driver_decoupling_price = 0.0197            # USD
    shift_register_outputs = 8                  # count
    gate_driver_half_bridges = 3                # count
    gate_driver_price = 0.2254                  # USD
    power_mosfet_price = 0.075                  # USD per dual N-MOSFET package; historical RFQ allowance, sourcing unverified
    shift_register_clock_rating = 20000000      # bits/s (74HC datasheet worst-case f_max at 4.5V, not the typical figure)
    shift_register_power_capacitance = 4.2e-11  # F
    shift_register_price = 0.028                # USD
    driver_serial_clock = 40000000              # bits/s
    smt_assembly_cost_per_joint = 0.0017        # USD
    max_bus_current = 120                       # A per split rail; baseline busbar/cabling limit checked against modeled peak load
    bus_distribution_price = 36.96              # USD
    rail_clamp_price = 5.0                      # USD per rail/zone; active regenerative-energy clamp allowance, design and sourcing outstanding
    rail_bulk_capacitor_price = 4.0             # USD (zone-level electrolytic; sizing needs ripple/inductance spec) [TO BE SOURCED]
    driver_channels_per_bulk_capacitor = 29     # channels (keeps the former 4 capacitors / 116-channel local decoupling density)
    bulk_capacitor_price = 0.25                 # USD, 330-470uF polymer local decoupling [TO BE SOURCED]
    supercap_cell_capacitance = 350             # F (Maxwell BCAP0350 P270 S18 snap-in)
    supercap_cell_max_voltage = 2.7             # V
    supercap_cell_working_voltage = 2.4         # V (series-count derating for cell life)
    supercap_cell_esr = 0.0032                  # ohm
    supercap_eol_capacitance_fraction = 0.8     # ratio (vendor end-of-life definition: 80% of minimum capacitance)
    supercap_eol_esr_factor = 2.0               # ratio (vendor end-of-life definition: 200% of maximum ESR)
    supercap_cell_price = 7.65                  # USD (Maxwell BCAP0350-P270-S18, DigiKey 1k tier; allocation advised)
    supercap_cell_mass_kg = 0.065               # kg (distributor-listed)
    supercap_balancer_price_per_cell = 0.15     # USD (balancing network share) [TO BE SOURCED]
    supercap_oring_price = 4.0                  # USD per protected buffer fan-out path; device/FET count must be re-sized from the modelled rail current [TO BE SOURCED]
    supercap_management_price_per_rail = 20.0   # USD (series-stack monitor + precharge/charge path + fuse + disconnect per rail bank) [TO BE SOURCED]
    midpoint_balancer_price = 40.0              # USD, active split-rail midpoint balance/protection allowance [TO BE SOURCED]
    midpoint_balancer_mass_kg = 0.3             # kg, controller + magnetics + protection allowance
    midpoint_balancer_current_rating = 5.0      # A, handles calibrated residual rail imbalance rather than traction current
    bus_droop_fraction = 0.1                    # ratio (allowed rail sag during buffer-fed burst; half depletion, half ESR)
    radiator_aluminium_price_per_kg = 12.0      # USD (extruded integral-fin heatsink, RFQ budget)
    playing_surface_price = 12.0                # USD
    motor_pcb_price_per_cm2 = 0.01063           # USD area allowance; physical segmentation is deliberately not fixed at this stage
    usable_bus_voltage_fraction = 0.9           # ratio
    hall_pitch_candidates = (30.0, 25.0, 24.0, 20.0, 100 / 6, 16.0, 15.0, 100 / 7, 12.5, 12.0, 10.0) # mm, sparse->dense; edge rows/columns are cropped to the motor outline
    hall_observation_window_side = 4            # count
    hall_sensor_mux_channels = 16               # count
    hall_sensor_price = 0.34758                 # USD (TI DRV5055A4QDBZR catalog tier; production RFQ needed)
    hall_sensor_mux_price = 0.2527              # USD
    magnet_cost_per_kg = 384.0                  # USD/kg; historical magnet cost allowance, production sourcing outstanding
    hall_adc_sample_rate = 500000               # samples/s
    hall_adc_native_bits = 12                   # bits (MCU SAR ADC native resolution)
    hall_interpolation_bits = 14                # bits (effective, via oversampling above native)
    hall_package_standoff = 0.6                 # mm (SOT-23 sensing element below PCB underside)
    hall_power_settle_time = 0.0001             # s (gated sensor group power-up + RC settle before burst)
    hall_gate_switch_price = 0.0206             # USD (GOODWORK AO3401A catalog tier; production RFQ needed)
    thermal_sensor_area_mm2 = 5000              # mm2 of motor area per distributed temperature sensor
    thermal_sensor_price = 0.0091               # USD (10k 1% 0402 NTC, LCSC catalog class) [TO BE SOURCED]
    hall_supply_voltage = 5                     # V
    hall_supply_current = 0.01                  # A max (TI DRV5055A4 at 5V datasheet maximum; ~6mA typical)
    hall_sensitivity = 12.5                     # V/T (TI DRV5055A4 nominal at 5V)
    hall_output_noise = 1.84e-05                # T rms typical (130nT/sqrtHz * sqrt(20kHz)); not a guaranteed maximum
    hall_linear_range = 0.169                   # T (TI DRV5055A4 at 5V)
    hall_sensor_bandwidth = 20000               # Hz (DRV5055 small-signal bandwidth; bounds independent noise samples)
    coil_field_subtraction_error = 0.005        # ratio (residual after Hall-array self-calibration of coil map + channel offsets, idle-board recalibration)
    position_error_gap_fraction = 0.1           # ratio (docking/landing error budget as fraction of flight gap; applies at hover currents)
    flight_position_error_gap_fraction = 0.25   # ratio; in-transit position-error budget relative to flight gap; neighbour clearance still requires verification
    pcb_copper_plane_thickness = 0.07           # mm (two 1oz solid planes in the 4-layer motor/control PCB allowance)
    radiator_standoff_below_pcb = 1.3           # mm (gap-filler bond line; clears 1.1mm SOT-23 Hall bodies under the PCB)
    radiator_slot_pitch = 5                     # mm (crosshatch eddy-break kerfs, island size)
    radiator_slot_web_thickness = 0.5           # mm (solid web left at plate bottom under the kerfs)
    radiator_slotting_price = 200.0             # USD (gang-saw crosshatch kerf pass on extrusion base, mid RFQ budget)
    potting_epoxy_price = 45.0                  # USD (alumina-filled 2.5 W/mK, coil bed allowance, RFQ budget)
    gap_filler_pad_price = 336.43               # USD (Laird Tputty SF560 5.6 W/mK, 10-pail public price per board; RFQ + selective dispensing could cut 67-80%)
    gap_filler_density = 3.4                    # g/cc (Tputty SF560)
    windings_per_coil_body = 1                  # count
    pcb_thickness = 1.6                         # mm
    frame_enclosure_mass_kg = 1.0               # kg
    board_electronics_mass_kg = 0.3             # kg
    blocker_hops_per_gap_move = 4               # count (2 blockers aside and back per knight gap move)
    potting_density = 1.8                       # g/cc (filled epoxy)
    bus_distribution_mass_kg = 0.8              # kg (busbar + zone cabling)
    ac_input_price = 8.0                        # USD (IEC inlet + fuse + mains switch + internal AC harness) [TO BE SOURCED]
    emi_filter_price = 12.0                     # USD; mains EMI filter allowance, switching-frequency suitability requires validation [TO BE SOURCED]
    enclosure_price = 40.0                      # USD (frame + skirt enclosure, 1.0kg mass already budgeted) [TO BE SOURCED]
    piece_control_flops = 20000                 # flop/update
    setpoint_dma_words_flops = 4                # flop per setpoint word (pack + DMA descriptor, FPGA does the delta-sigma)
    board_setpoint_fpga_count = 1               # count (one logical-board command engine; physical placement/partition remains open)
    board_setpoint_fpga_price = 25.0            # USD allowance for >=55kbit state RAM + parallel serializers [TO BE SOURCED / SYNTHESIS REQUIRED]
    board_setpoint_fpga_power = 1.0             # W allowance [TO BE VERIFIED BY SYNTHESIS]
    board_setpoint_fpga_solder_joints = 144     # count allowance
    control_node_adc_engines = 2                # independent Hall scan engines per regional MCU
    min_hall_scan_headroom = 1.1                # ratio
    min_control_compute_headroom = 2.0          # ratio
    control_node_mcu_price = 3.13               # USD, STM32G431KBT6 class
    control_node_mcu_solder_joints = 32         # count
    node_mcu_throughput_mflops = 170            # Mflop/s
    control_node_mcu_power = 0.4                # W
    host_power = 8                              # W
    psu_sizing_margin = 1.1                     # ratio; supply-sizing reserve above the modeled sustained hot-load requirement
    psu_family = 'Mean Well UHP-2500-36 adjusted to 40V' # retained supply model and voltage adjustment; hardware baseline, not a new selection
    psu_rating = 2498.4                         # W, full-bus continuous rating
    psu_price = 589.0                           # USD, DigiKey single-unit public price; RFQ at 100 boards
    psu_mass_kg = 4.07                          # kg, manufacturer packing specification
    psu_url = 'https://www.digikey.com/en/products/detail/mean-well-usa-inc/UHP-2500-36/11494555' # historical supply listing used for the BOM; not a refreshed quotation
    sliding_friction_coefficient = 0.3          # ratio; provisional kinetic friction during contact reset, requires surface/piece measurements
    minimum_contact_normal_fraction = 0.1       # fraction of piece weight that must remain supported by the board during reset
    coil_winding_clearance = 0.02               # mm; total radial clearance reserved beyond insulated wire width in each winding wall
    material_reference_temperature = 20.0       # C; reference for the copper-resistivity and magnet-remanence temperature models
    thermal_trace_step = 0.05                   # s; maximum integration step for transient plate/local heating
    shunt_power_derating = 0.5                  # fraction of nominal shunt power rating allowed by the dissipation check
    max_control_delay_fraction = 0.1            # fraction of the unstable growth time allowed for the ideal current-slew screen
    field_grid_samples = 41                     # samples per axis for the reference-plane magnetic-field grid
    matrix_rank_tolerance = 1e-9                # relative threshold, scaled by the largest matrix entry, for actuator/library rank
    singular_value_tolerance = 1e-12            # relative SVD cutoff for condition estimates; also a norm cutoff for normalized mode-library columns
    hall_rank_tolerance = 1e-6                  # relative threshold, scaled by the largest Jacobian entry, for Hall observability rank
    allocator_tolerance = 1e-11                 # SLSQP objective/convergence tolerance for normalized minimum-loss allocation
    allocator_residual_tolerance = 1e-7         # normalized constraint tolerance; also the LP primal/dual feasibility tolerance
    allocator_limit_tolerance = 1e-8            # relative numerical tolerance on allocated channel-current limits
    allocator_max_iterations = 300              # maximum SLSQP iterations; failure raises instead of substituting another solution
    position_derivative_step = 2e-5             # m; centered finite-difference displacement for six-axis mechanical stiffness
    hall_position_derivative_step = 1e-5        # m; centered finite-difference displacement for the Hall field Jacobian
    angle_derivative_step = 1e-4                # rad; centered finite-difference rotation for stiffness and Hall Jacobians
    nominal_force_mesh = 16                     # magpylib-force polyline meshing setting for nominal actuation calculations
    pose_force_mesh = 12                        # magpylib-force polyline meshing setting for the flight pose sweep
    verification_force_mesh = 8                 # magpylib-force polyline meshing setting for selected-coil authority and contact checks
    current_demand_mesh_refinements = (1, 2)    # diagnostic multipliers for segment, radial and axial resolution at the worst flight pose
    active_window_phase_samples = 6             # equally spaced samples across the combined coil-lattice repeat; handoff planes are additionally sampled
    active_window_handoff_offsets = (0.001, 0.0001, 0.00001) # m; shrinking distances on either side of a coil-window handoff for continuity diagnosis
    active_window_transition_fraction = 0.5     # fraction of the closest handoff-plane spacing used as the full smooth-blend width; must be between zero and one
    coil_radial_filaments = 2                   # filament samples across each winding wall in the finite-coil approximation
    max_coil_axial_filaments = 4                # upper bound on filament layers through the winding height
    axial_filament_spacing = 0.001              # m; target axial spacing used to choose the number of filament layers
    coil_coupling_heights_mm = (0.05, 0.5, 1.0, 2.0, 3.0, 4.0, 5.0, 7.0, 10.0) # mm; simulated coil heights defining the coupling interpolation domain
    pose_yaws_deg = (0, 45, 90)                 # deg; yaw orientations sampled for flight and contact allocations
    pose_phase_fractions = (0.0, 0.25, 0.5)     # fractions of the relevant coil/sensor pitch sampled in each lateral direction
    pose_tilt_fractions = (1.0, 0.5)            # fractions of the rim-clearance-limited tilt used for authority verification
    maximum_rim_sine = 0.95                     # dimensionless upper bound on the rim-drop/radius ratio before arcsine
    horizontal_force_directions = 8             # equally spaced horizontal demand directions around a full circle
    neighbour_yaws_deg = tuple(range(0, 91, 15)) # deg; sampled neighbour orientations for the powered-off snap-force screen
    neighbour_force_mesh = (4, 4, 4)            # cuboid mesh subdivisions along x, y and z for mutual-magnet force/torque
    eddy_force_mesh = (3, 3, 3)                 # cuboid mesh subdivisions along x, y and z for conductive-sheet image-force estimates
    mode_counts = (6, 8, 10, 12, 16, 20, 23)    # candidate current-basis sizes for the optional local mode-compression diagnostic
    setpoint_snr_bits_coefficient = 6.02        # dB per bit in the assumed delta-sigma setpoint resolution estimate
    setpoint_snr_offset = 13.0                  # dB offset in the assumed delta-sigma setpoint oversampling estimate
    setpoint_snr_oversampling_coefficient = 15.0 # dB per doubling of oversampling in the assumed setpoint resolution estimate
    wire_price_per_kg = 18.74                   # USD/kg; historical rectangular magnet-wire cost allowance, supplier quote outstanding
    piece_plastic_price = 1.4                   # USD per piece; shell material, inserts and finish allowance
    host_price = 61.96                          # USD per host compute module; historical BOM allowance
    host_carrier_price = 25.0                   # USD per host carrier/mainboard; historical BOM allowance
    report_scientific_lower_bound = 1e-3        # absolute nonzero value below which reports use scientific notation
    report_scientific_upper_bound = 1e6         # absolute value at or above which reports use scientific notation
    report_precision = 4                        # decimal places in fixed notation, significant digits in scientific notation
    report_label_width = 42                     # characters; minimum report label-column width
    power_mosfet_solder_joints = 8              # SMT solder joints per dual-MOSFET package for assembly cost
    gate_driver_solder_joints = 20              # SMT solder joints per gate-driver IC for assembly cost
    shift_register_solder_joints = 16           # SMT solder joints per shift-register IC for assembly cost
    setpoint_filter_solder_joints = 4           # SMT solder joints per two-component setpoint filter for assembly cost
    comparator_solder_joints = 8                # SMT solder joints per current-comparator IC for assembly cost
    passive_solder_joints = 2                   # SMT solder joints per two-terminal passive component
    hall_sensor_solder_joints = 3               # SMT solder joints per Hall sensor for assembly cost
    hall_mux_solder_joints = 24                 # SMT solder joints per Hall multiplexer for assembly cost
    gate_switch_solder_joints = 3               # SMT solder joints per Hall-group power switch for assembly cost
    coil_solder_joints = 2                      # winding termination joints per installed coil body for assembly cost
    gate_passives_per_half_bridge = 2           # gate passive components budgeted per half-bridge
    driver_half_bridges_per_coil = 1            # half-bridge channels per coil in the midpoint-return drive topology
    coil_bus_voltage_fraction = 0.5             # fraction of full bus available to one coil before voltage-headroom derating
    minimum_axial_filaments = 1                 # lower bound on filament layers through the winding height
    force_gradient_step = 1e-5                  # m; spatial finite-difference step passed to magpylib-force getFT
    thermal_convergence_tolerance = 1e-8        # C; temperature-change tolerance for steady/periodic thermal iteration
    thermal_max_iterations = 100                # maximum steady/periodic thermal iterations; nonconvergence raises
    cad_geometry_tolerance = 0.001              # mm; CAD bounding-box, clearance and STEP round-trip comparison tolerance
    cad_exploded_layer_spacing = 5              # mm; additional separation per layer in the illustrative exploded view only
    cad_preview_size = (1600, 1000)             # pixels; exported FreeCAD preview width and height
    cad_preview_margin = 1.2                    # ratio; camera-height expansion after fitting the CAD preview
    cad_overlay_transparency = 85               # percent; translucent stack overlays in FreeCAD, with no physical meaning


class Constants:
    # Board definition and physical/material reference values; units are explicit for each entry.
    board_squares_per_side = 8                  # chess squares along each side of the playing area
    ndfeb_remanence_br = 1.36                   # T; baseline N48SH remanence at material_reference_temperature; supplier grade/lot verification outstanding
    ndfeb_br_tempco = -0.0011                   # 1/K; assumed reversible NdFeB remanence coefficient relative to material_reference_temperature
    ndfeb_density = 0.0075                      # g/mm3; NdFeB mass density
    plastic_density = 0.0012                    # g/mm3; piece-shell material density
    copper_resistivity = 1.724e-08              # ohm.m; copper resistivity at material_reference_temperature
    copper_resistivity_tempco = 0.00393         # 1/K; copper resistivity coefficient relative to material_reference_temperature
    aluminium_resistivity = 2.82e-08            # ohm.m; baseline aluminium resistivity for the conductive-sheet drag model
    copper_density = 8960                       # kg/m3; copper mass density
    gravity = 9.80665                           # m/s2; gravitational acceleration
    vacuum_permeability = 1.25663706e-06        # H/m; magnetic permeability of vacuum
    fr4_density = 0.00185                       # g/mm3; PCB laminate mass density


if __name__ == "__main__":
    from methodology.design import main

    main()
